site_name: Sujeethan Vigneswaran
theme:
  name: material
  palette: 
    scheme: slate
    primary: white
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - toc.integrate
nav:
  - Home: 'index.md'
  - 'Blog':
    - 'Mac Create Windows Installation USB' : 'blog/mac-create-windows-bootable-usb.md'
    - 'Mac Stop Sleeping' : 'blog/mac-stop-sleeping.md'
plugins:
  - search:
      lang: en
extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sujeethan-vigneswaran/
      name: Sujee on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/itssujee
      name: Sujee on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/itssujee
      name: Sujee on Twitter
    - icon: fontawesome/solid/envelope
      link: mailto:sujeethan.vigneswaran@gmail.com
      name: Sujee on Email
copyright: Designed by Sujee in Canada 🇨🇦

