site_name: Sujeethan Vigneswaran
extra_css: [extra.css]
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette: 
    scheme: default
    primary: indigo
    accent: indigo
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/images/favicon.ico
  features:
  - header.autohide
  plugins:
    - search
    - social:
      cards_layout: default
      cards_dir: assets/images/social
repo_name: itssujee/homepage
repo_url: https://github.com/itssujee/itssujee.github.io
extra:
  analytics:
    provider: google
    property: G-TD4D3HM7LG
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sujeethan-vigneswaran/
      name: Sujee on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/itssujee
      name: Sujee on GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:sujeethan.vigneswaran@gmail.com
      name: Sujee on Email
markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: Designed by Sujee in Canada 🇨🇦

